feat!: remove ServiceMonitor CRD
camptocamp/devops-stack-module-cert-manager pull request #46
Opened 2023-05-05 14:12 UTC by ckaenzig

## Description of the changes

feat!: remove ServiceMonitor CRD. It causes conflict issues with the CRD installed by the kube-prometheus-stack chart when the verisons are not in sync. It's a bad solution to include the CRD in this module.

This was found because the latest kube-prometheus-chart adds a `attachMetadata` parameter in the ServiceMonitor spec, and the non up-to-date CRD in this module causes Argo CD to keep the resource out-of-sync indefinitely.

## Breaking change

- [x ] Yes (in our custom resources in the templates directory of this module)

## Tests executed on which distribution(s)

- [ ] KinD
- [ ] AKS (Azure)
- [ ] EKS (AWS)
- [ ] Scaleway
- [ ] SKS (Exoscale)

2023-05-11 15:28 UTC, ckaenzig commented
I added a variable `enable_service_monitor` to address the missing CRD issue when necessary. As discussed, we could add a similar variable to other modules that deploy such resources.

2023-05-11 15:32 UTC, ckaenzig commented
... aaand I rebased on main to cleanup the commits in this branch.

2023-05-12 06:09 UTC, lentidas approved these changes
Thank you, @ckaenzig, that was exactly what I was thinking about. I proposed a reword in the comment. Other than that everything looks good.

2023-05-12 06:09 UTC, lentidas commented on variables.tf
> +  description = "Enable prometheus ServiceMonitor in helm chart."
```suggestion
  description = "Enable Prometheus ServiceMonitor in the Helm chart."
```

2023-05-12 07:02 UTC, jbarascut approved these changes

2023-05-12 07:37 UTC, lentidas requested changes
Sorry, one important thing I forgot before!

We need to add a way to propagate the variable from the variants to the root module when instantiating cert-manager from a variant. For example, in the [`eks/main.tf`](./eks/main.tf):

module "cert-manager" {
  source = "../"

  cluster_name     = var.cluster_name
  base_domain      = var.base_domain
  argocd_namespace = var.argocd_namespace

  namespace              = var.namespace
  target_revision        = var.target_revision
  deep_merge_append_list = var.deep_merge_append_list
  app_autosync           = var.app_autosync
  enable_service_monitor = var.enable_service_monitor # THIS LINE

  helm_values = concat(local.helm_values, var.helm_values)

  dependency_ids = var.dependency_ids
}
```

2023-05-12 12:33 UTC, ckaenzig commented
> We need to add a way to propagate the variable from the variants to the root module when instantiating cert-manager from a variant

Good catch, thanks! I added this as well as your suggested change for the variable description.

2023-05-15 09:45 UTC, merged